# Generated by Django 4.0.5 on 2022-06-21 16:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('description', models.TextField(max_length=500, verbose_name='description')),
                ('thumbnail', models.FileField(upload_to='product/', verbose_name='thumbnail')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='start_date')),
                ('end_date', models.DateTimeField(default=datetime.datetime(2022, 6, 21, 16, 14, 43, 443318), verbose_name='end_date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
