# Generated by Django 4.0.5 on 2022-06-22 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='start_date',
        ),
        migrations.AddField(
            model_name='product',
            name='exposure_end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 28, 15, 47, 54, 937703), verbose_name='exposure_end_date'),
        ),
        migrations.AddField(
            model_name='product',
            name='exposure_start_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='exposure_start_date'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is_active'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
    ]
