# Generated by Django 4.0.5 on 2022-06-20 10:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 10, 53, 17, 774191, tzinfo=utc)),
        ),
    ]
