# Generated by Django 4.0.5 on 2022-06-20 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_article_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 20, 13, 53, 539843)),
        ),
        migrations.AlterField(
            model_name='article',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
