# Generated by Django 4.0.5 on 2022-06-20 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_dish',
            field=models.ManyToManyField(to='User.dish', verbose_name='favorite_dish'),
        ),
    ]
